[package]
name = "query"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.11"
rocket_codegen = "0.4.11"
http = "0.2"
reqwest = { version = "0.11", features = ["blocking","json"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4.24"

tokio = { version = "1", features = ["full"] }  # for our async runtime
